# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
g = [Array.new, Array.new, Array.new, Array.new]
s = [[Array.new, Array.new, Array.new, Array.new], [Array.new, Array.new, Array.new, Array.new], [Array.new, Array.new, Array.new]]
c0 = Category.create(name: 'The Legend of Zelda: Skyword Sword', image: 'zeldaSS.jpg')
g[0][0] = Game.create(name: 'The Legend of Zelda: A Link Between Worlds', image: 'zeldaALBW.jpg', bio: 'a cool game', category_id: c0.id)
s[0][0][0] = Song.create(name: 'Another Triforce', audio: '/assets/link-between-worlds-another-triforce.mp3', game_id: g[0][0].id)
s[0][0][1] = Song.create(name: 'Becoming a Painting', audio: '/assets/link-between-worlds-becoming-a-painting.mp3', game_id: g[0][0].id)
s[0][0][2] = Song.create(name: 'Before the Final Battle', audio: '/assets/link-between-worlds-before-the-final-battle.mp3', game_id: g[0][0].id)
s[0][0][3] = Song.create(name: 'Boss Battle Hyrule', audio: '/assets/link-between-worlds-boss-battle-hyrule-.mp3', game_id: g[0][0].id)

g[0][1] = Game.create(name: 'Super Mario Galaxy', image: 'marioGalaxy.png', bio: 'a cool game', category_id: c0.id)
s[0][1][0] = Song.create(name: 'Overture', audio: '/assets/smg-101-overture.mp3', game_id: g[0][1].id)
s[0][1][1] = Song.create(name: 'Starbit Festival', audio: '/assets/smg-102-starbit-festival.mp3', game_id: g[0][1].id)
s[0][1][2] = Song.create(name: "Attack! Koopa's Fleet", audio: '/assets/smg-103-attack-koopa-s-fleet.mp3', game_id: g[0][1].id)
s[0][1][3] = Song.create(name: 'Catastrophe', audio: '/assets/smg-104-catastrophe.mp3', game_id: g[0][1].id)
s[0][1][4] = Song.create(name: "Peach's Castle is Stolen", audio: '/assets/smg-105-peach-s-castle-is-stolen.mp3', game_id: g[0][1].id)
s[0][1][5] = Song.create(name: 'Into the Galaxy', audio: '/assets/smg-106-into-the-galaxy.mp3', game_id: g[0][1].id)
s[0][1][6] = Song.create(name: 'Egg Planet', audio: '/assets/smg-107-egg-planet.mp3', game_id: g[0][1].id)
s[0][1][7] = Song.create(name: "Rosetta's Comet Observatory", audio: '/assets/smg-108-rosetta-s-comet-observatory-1.mp3', game_id: g[0][1].id)

g[0][2] = Game.create(name: 'Okami', image: 'okami.jpg', bio: '', category_id: c0.id)
s[0][2][0] = Song.create(name: 'Title', audio: '/assets/okami-101-Title.mp3', game_id: g[0][2].id)
s[0][2][1] = Song.create(name: 'Title Call', audio: '/assets/okami-102-Title-Call.mp3', game_id: g[0][2].id)
s[0][2][2] = Song.create(name: 'The Beginning', audio: '/assets/okami-103-The-Beginning.mp3', game_id: g[0][2].id)
s[0][2][3] = Song.create(name: 'Prologue', audio: '/assets/okami-104-Prologue.mp3', game_id: g[0][2].id)
s[0][2][4] = Song.create(name: 'Sinister Design', audio: '/assets/okami-105-Sinister-Design.mp3', game_id: g[0][2].id)
s[0][2][5] = Song.create(name: "Yamato-no-Orochi's Revival", audio: "/assets/okami-106-Yamato-no-Orochi's-Revival.mp3", game_id: g[0][2].id)
s[0][2][6] = Song.create(name: "The Great Goddess Amaterasu's Revival", audio: "/assets/okami-107-The-Great-Goddess-Amaterasu's-Revival.mp3", game_id: g[0][2].id)
s[0][2][7] = Song.create(name: "Oira's Theme", audio: "/assets/okami-108-Oira's-Theme.mp3", game_id: g[0][2].id)
s[0][2][8] = Song.create(name: 'Curse', audio: '/assets/okami-109-Curse.mp3', game_id: g[0][2].id)
s[0][2][9] = Song.create(name: 'Izanagi Cavern', audio: '/assets/okami-110-Izanagi-Cavern.mp3', game_id: g[0][2].id)
s[0][2][10] = Song.create(name: 'Looking Up at the Starry Sky', audio: '/assets/okami-111-Looking-Up-at-the-Starry-Sky.mp3', game_id: g[0][2].id)
s[0][2][11] = Song.create(name: 'Constellation (Dragon Sketch)', audio: '/assets/okami-112-Constellation-(Dragon-Sketch).mp3', game_id: g[0][2].id)
s[0][2][12] = Song.create(name: 'Constellation Complete', audio: '/assets/okami-113-Constellation-Complete.mp3', game_id: g[0][2].id)
s[0][2][13] = Song.create(name: 'Painting God Appearance', audio: '/assets/okami-114-Painting-God-Appearance.mp3', game_id: g[0][2].id)
s[0][2][14] = Song.create(name: 'Talking with the Painting God', audio: '/assets/okami-115-Talking-with-the-Painting-God.mp3', game_id: g[0][2].id)
s[0][2][15] = Song.create(name: 'Painting Piece', audio: '/assets/okami-116-Painting-Piece.mp3', game_id: g[0][2].id)

g[0][3] = Game.create(name: 'HALO: Combat Evolved', image: 'halo.jpg', bio: 'a cool game', category_id: c0.id)
s[0][3][0] = Song.create(name: "Opening Suite", audio: "/assets/halo-01.-Opening-Suite-_Martin-O'Donnell-_-Michael-Salvatori_.mp3", game_id: g[0][3].id)
s[0][3][1] = Song.create(name: "Truth and Reconciliation Suite", audio: "/assets/halo-02.-Truth-and-Reconciliation-Suite-_Martin-O'Donnell-_-Michael-Salvatori_.mp3", game_id: g[0][3].id)
s[0][3][2] = Song.create(name: "Brothers in Arms", audio: "/assets/halo-03.-Brothers-in-Arms-_Martin-O'Donnell-_-Michael-Salvatori_.mp3", game_id: g[0][3].id)
s[0][3][3] = Song.create(name: "Enough Dead Heroes", audio: "/assets/halo-04.-Enough-Dead-Heroes-_Martin-O'Donnell-_-Michael-Salvatori_.mp3", game_id: g[0][3].id)
s[0][3][4] = Song.create(name: "Perilous Journey", audio: "/assets/halo-05.-Perilous-Journey-_Martin-O'Donnell-_-Michael-Salvatori_.mp3", game_id: g[0][3].id)
s[0][3][5] = Song.create(name: "A Walk in the Woods", audio: "/assets/halo-06.-A-Walk-in-the-Woods-_Martin-O'Donnell-_-Michael-Salvatori_.mp3", game_id: g[0][3].id)
s[0][3][6] = Song.create(name: "Ambient Wonder", audio: "/assets/halo-07.-Ambient-Wonder-_Martin-O'Donnell-_-Michael-Salvatori_.mp3", game_id: g[0][3].id)
s[0][3][7] = Song.create(name: "The Gun Pointed at the Head of the Universe", audio: "/assets/halo-08.-The-Gun-Pointed-at-the-Head-of-the-Universe-_Martin-O'Donnell-_-Michael-Salvatori_.mp3", game_id: g[0][3].id)

c1 = Category.create(name: 'Undertale', image: 'undertale.jpg')
g[1][0] = Game.create(name: 'Super Paper Mario', image: 'superPaperMario.jpg', bio: '', category_id: c1.id)
s[1][0][0] = Song.create(name: "Today's Story", audio: '/assets/spm-1-01-today-s-story.mp3', game_id: g[1][0].id)
s[1][0][1] = Song.create(name: 'The Wedding Begins', audio: '/assets/spm-1-02-the-wedding-begins.mp3', game_id: g[1][0].id)
s[1][0][2] = Song.create(name: 'Wedding Waltz', audio: '/assets/spm-1-03-wedding-waltz.mp3', game_id: g[1][0].id)
s[1][0][3] = Song.create(name: 'Birth of the Chaos Heart', audio: '/assets/spm-1-04-birth-of-the-chaos-heart.mp3', game_id: g[1][0].id)
s[1][0][4] = Song.create(name: 'Champion of Destruction', audio: '/assets/spm-1-05-champion-of-destruction.mp3', game_id: g[1][0].id)
s[1][0][5] = Song.create(name: 'Super Paper Mario', audio: '/assets/spm-1-06-super-paper-mario.mp3', game_id: g[1][0].id)
s[1][0][6] = Song.create(name: 'Mario Bros. House', audio: '/assets/spm-1-07-mario-bros.-house.mp3', game_id: g[1][0].id)
s[1][0][7] = Song.create(name: 'Evil King Bowser Here', audio: '/assets/spm-1-08-evil-king-bowser-here.mp3', game_id: g[1][0].id)
s[1][0][8] = Song.create(name: 'The Ultimate Show [Final Battle]', audio: '/assets/spm-3-21-the-ultimate-show-final-battle-.mp3', game_id: g[1][0].id)

g[1][1] = Game.create(name: 'Earthbound', image: 'earthbound.jpg', bio: '', category_id: c1.id)
s[1][1][0] = Song.create(name: 'The Evil Gygas Attacks! (part 1)', audio: '/assets/001-the-evil-giygas-attacks-part-1.mp3', game_id: g[1][1].id)
s[1][1][1] = Song.create(name: 'The Evil Gygas Attacks! (part 2)', audio: '/assets/002-the-evil-giygas-attacks-part-2.mp3', game_id: g[1][1].id)
s[1][1][2] = Song.create(name: 'Title Screen', audio: '/assets/003-title-screen.mp3', game_id: g[1][1].id)
s[1][1][3] = Song.create(name: 'Opening Credits', audio: '/assets/004-opening-credits.mp3', game_id: g[1][1].id)
s[1][1][4] = Song.create(name: 'Choose a File', audio: '/assets/005-choose-a-file.mp3', game_id: g[1][1].id)
s[1][1][5] = Song.create(name: 'Your Name, Please', audio: '/assets/006-your-name-please.mp3', game_id: g[1][1].id)
s[1][1][6] = Song.create(name: 'Your Name, Please (noiseless)', audio: '/assets/007-your-name-please-noiseless.mp3', game_id: g[1][1].id)
s[1][1][7] = Song.create(name: "Now, Let's Go!", audio: '/assets/008-now-let-s-go.mp3', game_id: g[1][1].id)

g[1][2] = Game.create(name: 'Chrono Trigger', image: 'chronoTrigger.jpg', bio: '', category_id: c1.id)
s[1][2][0] = Song.create(name: 'A Presntiment', audio: '/assets/ct-01-A-Presentiment.mp3', game_id: g[1][2].id)
s[1][2][1] = Song.create(name: 'Chrono Trigger', audio: '/assets/ct-02-Chrono-Trigger.mp3', game_id: g[1][2].id)
s[1][2][2] = Song.create(name: 'Morning Sunlight', audio: '/assets/ct-03-Morning-Sunlight.mp3', game_id: g[1][2].id)
s[1][2][3] = Song.create(name: 'Peaceful Days', audio: '/assets/ct-04-Peaceful-Days.mp3', game_id: g[1][2].id)
s[1][2][4] = Song.create(name: 'Memories of Green', audio: '/assets/ct-05-Memories-of-Green.mp3', game_id: g[1][2].id)
s[1][2][5] = Song.create(name: 'Guardia Millenial Fair', audio: '/assets/ct-06-Guardia-Millenial-Fair.mp3', game_id: g[1][2].id)
s[1][2][6] = Song.create(name: "Gato's Song", audio: "/assets/ct-07-Gato's-Song.mp3", game_id: g[1][2].id)
s[1][2][7] = Song.create(name: 'A Strange Happening', audio: '/assets/ct-08-A-Strange-Happening.mp3', game_id: g[1][2].id)
s[1][2][8] = Song.create(name: 'Longing of the Wind', audio: '/assets/ct-09-Longing-of-the-Wind.mp3', game_id: g[1][2].id)
s[1][2][9] = Song.create(name: 'Goodnight', audio: '/assets/ct-10-Goodnight.mp3', game_id: g[1][2].id)
s[1][2][10] = Song.create(name: 'Secret of the Forest', audio: '/assets/ct-11-Secret-of-Forest.mp3', game_id: g[1][2].id)
s[1][2][11] = Song.create(name: 'Battle 1', audio: '/assets/ct-12-Battle-1.mp3', game_id: g[1][2].id)
s[1][2][12] = Song.create(name: 'Courage and Pride', audio: '/assets/ct-13-Courage-and-Pride.mp3', game_id: g[1][2].id)
s[1][2][13] = Song.create(name: 'Huh?!', audio: '/assets/ct-14-Huh_!.mp3', game_id: g[1][2].id)
s[1][2][14] = Song.create(name: 'Manoria Cathedral', audio: '/assets/ct-15-Manoria-Cathedral.mp3', game_id: g[1][2].id)
s[1][2][15] = Song.create(name: 'A Prayer to the Travelers', audio: '/assets/ct-16-A-Prayer-to-the-Travelers.mp3', game_id: g[1][2].id)

g[1][3] = Game.create(name: 'Shovel Knight', image: 'shovelKnight.png', bio: '', category_id: c1.id)
s[1][3][0] = Song.create(name: 'Main Theme', audio: '/assets/sk-01-main-theme.mp3', game_id: g[1][3].id)
s[1][3][1] = Song.create(name: 'Steel Thy Shovel', audio: '/assets/sk-02-steel-thy-shovel.mp3', game_id: g[1][3].id)
s[1][3][2] = Song.create(name: 'One Fateful Knight', audio: '/assets/sk-03-one-fateful-knight.mp3', game_id: g[1][3].id)
s[1][3][3] = Song.create(name: 'Strike the Earth! (Plains of Passage)', audio: '/assets/sk-04-strike-the-earth-plains-of-passage-.mp3', game_id: g[1][3].id)
s[1][3][4] = Song.create(name: 'The Rival (Black Knight - First Battle)', audio: '/assets/sk-05-the-rival-black-knight-first-battle-.mp3', game_id: g[1][3].id)
s[1][3][5] = Song.create(name: 'For Shovelry! (Boss Victory)', audio: '/assets/sk-06-for-shovelry-boss-victory-.mp3', game_id: g[1][3].id)
s[1][3][6] = Song.create(name: 'The Starlit Wilds (Campfire Scene)', audio: '/assets/sk-07-the-starlit-wilds-campfire-scene-.mp3', game_id: g[1][3].id)
s[1][3][7] = Song.create(name: 'The Adventure Awaits (Map Screen)', audio: '/assets/sk-08-the-adventure-awaits-map-screen-.mp3', game_id: g[1][3].id)

c2 = Category.create(name: 'FAST Racing NEO', image: 'fast.jpg')
g[2][0] = Game.create(name: 'F-Zero GX', image: 'fzeroGX.jpg', bio: '', category_id: c2.id)
s[2][0][0] = Song.create(name: 'Feel Our Pain (Fire Field)', audio: '/assets/fz-209-feel-our-pain-fire-field-.mp3', game_id: g[2][0].id)
s[2][0][1] = Song.create(name: 'Eight Guitars (Sand Ocean)', audio: '/assets/fz-221-8-guitars-sand-ocean-.mp3', game_id: g[2][0].id)
s[2][0][2] = Song.create(name: 'Like A Snake (Port Town)', audio: '/assets/fz-222-like-a-snake-port-town-.mp3', game_id: g[2][0].id)
s[2][0][3] = Song.create(name: 'Planet Colors (Green Plant)', audio: '/assets/fz-223-planet-colors-green-plant-.mp3', game_id: g[2][0].id)
s[2][0][4] = Song.create(name: 'Zen (Aeropolis)', audio: '/assets/fz-224-zen-aeropolis-.mp3', game_id: g[2][0].id)
s[2][0][5] = Song.create(name: 'For the Glory (Mute City)', audio: '/assets/fz-225-for-the-glory-feat.-mutecity-s-theme-mute-city-.mp3', game_id: g[2][0].id)
s[2][0][6] = Song.create(name: 'Osc-Sync Carnival (Lightning)', audio: '/assets/fz-226-osc-sync-carnival-lightning-.mp3', game_id: g[2][0].id)
s[2][0][7] = Song.create(name: 'Infinite Blue (Big Blue)', audio: '/assets/fz-227-infinite-blue-big-blue-.mp3', game_id: g[2][0].id)